In [6]:
import geopandas as gpd
import pandas as pd

In [4]:

# Load the world map data from GeoPandas
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))

# Save the GeoJSON file
output_geojson_path = './data/world_countries.geojson'
world.to_file(output_geojson_path, driver='GeoJSON')

/var/folders/3j/m9q0p_x54jz3fm02nml7dz740000gn/T/ipykernel_8509/632288119.py:2: FutureWarning: The geopandas.dataset module is deprecated and will be removed in GeoPandas 1.0. You can get the original 'naturalearth_lowres' data from https://www.naturalearthdata.com/downloads/110m-cultural-vectors/.
  world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))

In [7]:
df = pd.read_csv('./data/clean_data.csv')
world = gpd.read_file('./data/world_countries.geojson')

In [9]:
df.head()

,Unnamed: 0,show_id,type,title,country,release_year,duration,listed_in
0,0,s1,Movie,Dick Johnson Is Dead,United States,2020,90 min,Documentaries
1,1,s2,TV Show,Blood & Water,South Africa,2021,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,2,s3,TV Show,Ganglands,worldwide,2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
3,3,s4,TV Show,Jailbirds New Orleans,worldwide,2021,1 Season,"Docuseries, Reality TV"
4,4,s5,TV Show,Kota Factory,India,2021,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."

In [10]:
# Merge the CSV data with the GeoJSON data based on country names
merged_data = world.merge(df, how='left', left_on='name', right_on='country')

# Save the merged GeoJSON file
output_geojson_path = './data/world.geojson'
merged_data.to_file(output_geojson_path, driver='GeoJSON')

In [11]:
world2 = gpd.read_file('./data/world.geojson')

In [12]:
world2.head()

,pop_est,continent,name,iso_a3,gdp_md_est,Unnamed: 0,show_id,type,title,country,release_year,duration,listed_in,geometry
0,889953.0,Oceania,Fiji,FJI,5496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MULTIPOLYGON (((180.00000 -16.06713, 180.00000..."
1,58005463.0,Africa,Tanzania,TZA,63177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((33.90371 -0.95000, 34.07262 -1.05982..."
2,603253.0,Africa,W. Sahara,ESH,907,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-8.66559 27.65643, -8.66512 27.58948..."
3,37589262.0,North America,Canada,CAN,1736425,157.0,s158,Movie,Level 16,Canada,2018.0,102 min,"Sci-Fi & Fantasy, Thrillers","MULTIPOLYGON (((-122.84000 49.00000, -122.9742..."
4,37589262.0,North America,Canada,CAN,1736425,510.0,s511,TV Show,Between,Canada,2016.0,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","MULTIPOLYGON (((-122.84000 49.00000, -122.9742..."

In [13]:
world2 = world2.drop(columns=['iso_a3', 'gdp_md_est', 'Unnamed: 0'])
world2.head()

,pop_est,continent,name,show_id,type,title,country,release_year,duration,listed_in,geometry
0,889953.0,Oceania,Fiji,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MULTIPOLYGON (((180.00000 -16.06713, 180.00000..."
1,58005463.0,Africa,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((33.90371 -0.95000, 34.07262 -1.05982..."
2,603253.0,Africa,W. Sahara,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-8.66559 27.65643, -8.66512 27.58948..."
3,37589262.0,North America,Canada,s158,Movie,Level 16,Canada,2018.0,102 min,"Sci-Fi & Fantasy, Thrillers","MULTIPOLYGON (((-122.84000 49.00000, -122.9742..."
4,37589262.0,North America,Canada,s511,TV Show,Between,Canada,2016.0,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","MULTIPOLYGON (((-122.84000 49.00000, -122.9742..."